---
title: "2_preprocessing"
author: "Umberto Mignozzetti"
date: "12/25/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Adding articles

Teste

Este branch é o segundo.


```{r}
# Paper 343
dat <- data.frame(
  id = 343,
  published = 'Yes',
  title = 'Government spending and legislative organization: quasi-experimental evidence from germany',
  author = 'Egger and Koethenbuerger',
  year = 2010,
  journal = 'American Economic Journal: Applied Economics',
  web = 'https://www.jstor.org/stable/25760238',
  table = NA,
  column = NA,
  indepvar = NA,
  indepvar2 = NA,
  depvar = NA,
  depvar2 = NA,
  coef = NA,
  SE = NA
)

# Paper 367
dat <- rbind(dat,
  data.frame(
  id = 367,
  published = 'Yes',
  title = 'Spatially Targeted Government Spending and
Heterogeneous Constituent Cost Shares',
  author = 'Bradbury and Stephenson',
  year = 2009,
  journal = 'The Journal of Private Enterprise',
  web = 'http://journal.apee.org/index.php?title=Spring2009_6',
  table = 2,
  column = 2,
  indepvar = 'MEMSENATE',
  indepvar2 = 'K',
  depvar = 'Spending per capita',
  depvar2 = 'ExpPC',
  coef = 0.624,
  SE = 0.624/3.10
))

# Paper 585 K
dat <- rbind(dat,
  data.frame(
  id = 585,
  published = 'Yes',
  title = 'Legislative organization and government spending: cross-country evidence',
  author = 'Bradbury and Crain',
  year = 2001,
  journal = 'Journal of Public Economics',
  web = 'https://doi.org/10.1016/S0047-2727(00)00150-X',
  table = 2,
  column = 5,
  indepvar = 'Upper size',
  indepvar2 = 'K',
  depvar = 'Percent of GDP',
  depvar2 = 'PCTGDP',
  coef = 0.01262,
  SE = 0.01262/2.12
))

# Paper 585 N
dat <- rbind(dat,
  data.frame(
  id = 585,
  published = 'Yes',
  title = 'Legislative organization and government spending: cross-country evidence',
  author = 'Bradbury and Crain',
  year = 2001,
  journal = 'Journal of Public Economics',
  web = 'https://doi.org/10.1016/S0047-2727(00)00150-X',
  table = 2,
  column = 5,
  indepvar = 'Lower size',
  indepvar2 = 'N',
  depvar = 'Percent of GDP',
  depvar2 = 'PCTGDP',
  coef = 0.003627,
  SE = 0.003627/2.51
))

# Paper 1390
dat <- rbind(dat,
  data.frame(
  id = 1390,
  published = 'Yes',
  title = 'Electoral Systems and Public Spending',
  author = 'Milesi-Ferretti, Perotti, and Rostagno',
  year = 2001,
  journal = 'The Quarterly Journal of Economics',
  web = 'https://www.jstor.org/stable/pdf/2696437.pdf',
  table = 5,
  column = 1,
  indepvar = 'Log Avg Dist Magnitude',
  indepvar2 = 'logN',
  depvar = 'Percent of GDP',
  depvar2 = 'PCTGDP',
  coef = 1.05,
  SE = 1.05/1.10
))

# Paper 1390
dat <- rbind(dat,
  data.frame(
  id = 1390,
  published = 'Yes',
  title = 'Electoral Systems and Public Spending',
  author = 'Milesi-Ferretti, Perotti, and Rostagno',
  year = 2001,
  journal = 'The Quarterly Journal of Economics',
  web = 'https://www.jstor.org/stable/pdf/2696437.pdf',
  table = 5,
  column = 4,
  indepvar = 'Log Avg Dist Magnitude',
  indepvar2 = 'logN',
  depvar = 'Share transfer GDP',
  depvar2 = 'PCTTRF',
  coef = 1.70,
  SE = 1.70/3.49
))

# Paper 997
dat <- rbind(dat,
  data.frame(
  id = 997,
  published = 'No',
  title = 'Local government expenditure and council size: quasi-experimental evidence from japan',
  author = 'Hirota and Yunoue',
  year = 2012,
  journal = NA,
  web = 'https://mpra.ub.uni-muenchen.de/42799/1/MPRA_paper_42799.pdf',
  table = 3,
  column = 9,
  indepvar = 'logN',
  indepvar2 = 'logN',
  depvar = 'logExp',
  depvar2 = 'logExp',
  coef = 1.229,
  SE = 0.101
))

dat <- rbind(dat,
  data.frame(
  id = 974,
  published = 'No',
  title = 'Institutional arrangements and fiscal performance: the latin american experience',
  author = 'Stein, Talvi, and Grisanti',
  year = 1998,
  journal = 'NBER Working papers',
  web = 'https://www.nber.org/papers/w6358.pdf',
  table = 3,
  column = 1,
  indepvar = 'District magnitude',
  indepvar2 = 'logN',
  depvar = 'Proportion expenditure GDP',
  depvar2 = 'PCTGDP',
  coef = 0.0109,
  SE = 0.0143
))

dat <- rbind(dat,
  data.frame(
  id = 886,
  published = 'No',
  title = 'Electoral systems, legislative fragmentation and public spending: a comparative analysis of brazilian states',
  author = 'Lledo',
  year = 2003,
  journal = NA,
  web = 'http://lasa.international.pitt.edu/Lasa2003/LledoVictor.pdf',
  table = 6,
  column = 1,
  indepvar = 'Log (State Legislature Seats)',
  indepvar2 = 'logN',
  depvar = 'Primary Spending as a share of GSP',
  depvar2 = 'PCTGDP',
  coef = -4.69,
  SE = -4.69/(-1.75)
))

dat <- rbind(dat,
  data.frame(
  id = 849,
  published = 'No',
  title = 'Districts, spillovers, and government overspending',
  author = 'Baqir',
  year = 1999,
  journal = NA,
  web = 'http://documents.worldbank.org/curated/en/969221468781782275/pdf/multi-page.pdf',
  table = 3,
  column = 3,
  indepvar = 'Log (Council Size)',
  indepvar2 = 'logN',
  depvar = 'Log (Expenduture per capita)',
  depvar2 = 'logExpPC',
  coef = 0.302,
  SE = 0.302/7.885
))

dat <- rbind(dat,
  data.frame(
  id = 849,
  published = 'No',
  title = 'Districts, spillovers, and government overspending',
  author = 'Baqir',
  year = 1999,
  journal = NA,
  web = 'http://documents.worldbank.org/curated/en/969221468781782275/pdf/multi-page.pdf',
  table = 3,
  column = 6,
  indepvar = 'Log (Council Size)',
  indepvar2 = 'logN',
  depvar = 'Expenditure share',
  depvar2 = 'PCTGDP',
  coef = 2.066,
  SE = 2.066/7.014
))

dat <- rbind(dat,
  data.frame(
  id = 1415,
  published = 'No',
  title = 'Legislature size, bicameralism and government spending: evidence from democratic countries',
  author = 'Ricciuti',
  year = 2004,
  journal = NA,
  web = 'http://www.bemservizi.unito.it/repec/icr/wp2004/Ricciuti20-04.pdf',
  table = 3,
  column = 1,
  indepvar = 'House size',
  indepvar2 = 'N',
  depvar = 'Government spending',
  depvar2 = 'PCTGDP',
  coef = 0.014,
  SE = 0.012
))


dat <- rbind(dat,
  data.frame(
  id = 1415,
  published = 'No',
  title = 'Legislature size, bicameralism and government spending: evidence from democratic countries',
  author = 'Ricciuti',
  year = 2004,
  journal = NA,
  web = 'http://www.bemservizi.unito.it/repec/icr/wp2004/Ricciuti20-04.pdf',
  table = 3,
  column = 1,
  indepvar = 'Senate size',
  indepvar2 = 'K',
  depvar = 'Government spending',
  depvar2 = 'PCTGDP',
  coef = 0.016,
  SE = 0.012
))

dat <- rbind(dat,
  data.frame(
  id = 1415,
  published = 'No',
  title = 'Legislature size, bicameralism and government spending: evidence from democratic countries',
  author = 'Ricciuti',
  year = 2004,
  journal = NA,
  web = 'http://www.bemservizi.unito.it/repec/icr/wp2004/Ricciuti20-04.pdf',
  table = 3,
  column = 1,
  indepvar = 'S/H',
  indepvar2 = 'KN',
  depvar = 'Government spending',
  depvar2 = 'PCTGDP',
  coef = -7.612,
  SE = 5.354
))

dat <- rbind(dat,
  data.frame(
  id = 1309,
  published = 'Yes',
  title = 'Rethinking ward and at-large elections in cities: total spending, the number of locations of selected city services, and policy types',
  author = 'Langbein, Crewson, and Brasher',
  year = 1996,
  journal = 'Public Choice',
  web = 'https://link.springer.com/content/pdf/10.1007%2FBF00153234.pdf',
  table = 1,
  column = 1,
  indepvar = 'Number on city council',
  indepvar2 = 'N',
  depvar = 'Expenditures per capita',
  depvar2 = 'ExpPC',
  coef = 34.95,
  SE = 34.95/3.73
))

dat <- rbind(dat,
  data.frame(
  id = 578,
  published = 'Yes',
  title = 'Districting and Government Overspending',
  author = 'Baqir',
  year = 2002,
  journal = 'Public Choice',
  web = 'https://www.jstor.org/stable/pdf/10.1086/342804.pdf',
  table = 4,
  column = 4,
  indepvar = 'ln(Council Size)',
  indepvar2 = 'logN',
  depvar = 'ln(Government expenditure per capita)',
  depvar2 = 'logExpPC',
  coef = 0.1127,
  SE = 0.0373
))

dat <- rbind(dat,
  data.frame(
  id = 467,
  published = 'Yes',
  title = 'Institutional constraints on government spending',
  author = 'Primo',
  year = 2006,
  journal = 'Economics and Politics',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1468-0343.2006.00171.x',
  table = 5,
  column = 4,
  indepvar = 'Seats in lower chamber',
  indepvar2 = 'N',
  depvar = 'Real state and local expenditure per capita',
  depvar2 = 'ExpPC',
  coef = -0.82,
  SE = 0.19
))

dat <- rbind(dat,
  data.frame(
  id = 467,
  published = 'Yes',
  title = 'Institutional constraints on government spending',
  author = 'Primo',
  year = 2006,
  journal = 'Economics and Politics',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1468-0343.2006.00171.x',
  table = 5,
  column = 4,
  indepvar = 'Seats in upper chamber',
  indepvar2 = 'K',
  depvar = 'Real state and local expenditure per capita',
  depvar2 = 'ExpPC',
  coef = 0.97,
  SE = 0.74
))

dat <- rbind(dat,
  data.frame(
  id = 441,
  published = 'Yes',
  title = 'The law of k/n: the effect of chamber size on government spending in bicameral legislatures',
  author = 'Chen and Malhotra',
  year = 2007,
  journal = 'American Political Science Review',
  web = 'https://www.cambridge.org/core/services/aop-cambridge-core/content/view/E794E71F3182DAAEA2DA1328D45FDCC7/S0003055407070566a.pdf',
  table = 3,
  column = 1,
  indepvar = 'Lower chamber size',
  indepvar2 = 'N',
  depvar = 'Per capita expenditure',
  depvar2 = 'ExpPC',
  coef = -1.4,
  SE = 0.64
))

dat <- rbind(dat,
  data.frame(
  id = 441,
  published = 'Yes',
  title = 'The law of k/n: the effect of chamber size on government spending in bicameral legislatures',
  author = 'Chen and Malhotra',
  year = 2007,
  journal = 'American Political Science Review',
  web = 'https://www.cambridge.org/core/services/aop-cambridge-core/content/view/E794E71F3182DAAEA2DA1328D45FDCC7/S0003055407070566a.pdf',
  table = 3,
  column = 1,
  indepvar = 'Upper chamber size',
  indepvar2 = 'K',
  depvar = 'Per capita expenditure',
  depvar2 = 'ExpPC',
  coef = 8.3,
  SE = 2.35
))

dat <- rbind(dat,
  data.frame(
  id = 439,
  published = 'Yes',
  title = 'Legislative term limits and state spending',
  author = 'Erler',
  year = 2007,
  journal = 'Public Choice',
  web = 'https://www.jstor.org/stable/27698198',
  table = 2,
  column = 1,
  indepvar = 'Number of seats',
  indepvar2 = 'N',
  depvar = 'Expenditure per capita',
  depvar2 = 'ExpPC',
  coef = 3.93,
  SE = 1.18
))

dat <- rbind(dat,
  data.frame(
  id = 408,
  published = 'Yes',
  title = 'The impact of government structure on local public expenditures',
  author = 'MacDonald',
  year = 2008,
  journal = 'Public Choice',
  web = 'https://link.springer.com/content/pdf/10.1007/s11127-008-9308-8.pdf',
  table = 5,
  column = 3,
  indepvar = 'ln(Council Size)',
  indepvar2 = 'logN',
  depvar = 'Log Expenditure per capita',
  depvar2 = 'logExpPC',
  coef = 0.136,
  SE = 0.136/2.92
))

dat <- rbind(dat,
  data.frame(
  id = 288,
  published = 'Yes',
  title = 'Does the size of the legislature affect the size of government? evidence from two natural experimentss',
  author = 'Pettersson-Lidbom',
  year = 2012,
  journal = 'Journal of Public Economics',
  web = 'https://reader.elsevier.com/reader/sd/pii/S0047272711001319?token=45100FEA2EACE2CA32B3D4B12207371CDF7382DE23901C13F772F671CD7DF21671CE755BAA419EB3443B138C62CE37B2',
  table = 3,
  column = 5,
  indepvar = 'Council Size',
  indepvar2 = 'N',
  depvar = 'Log Expenditure per capita',
  depvar2 = 'logExpPC',
  coef = -0.159,
  SE = 0.041
))

dat <- rbind(dat,
  data.frame(
  id = 231,
  published = 'Yes',
  title = 'Coalition governments, cabinet size, and the common pool problem: evidence from the german states',
  author = 'Baskaran',
  year = 2013,
  journal = 'European Journal of Political Economy',
  web = 'https://reader.elsevier.com/reader/sd/pii/S0176268013000773?token=FECF22AE9B176134ACEB47AC0F11ACEFB1EA36D2D73BE992E1471732604540D3DCBD2D4A9CFDE2E44BE0B65C947FA4E3',
  table = 3,
  column = 4,
  indepvar = 'Parliament seats',
  indepvar2 = 'N',
  depvar = 'Real Expenditure per capita',
  depvar2 = 'ExpPC',
  coef = 0.974,
  SE = 0.974/1.743
))

dat <- rbind(dat,
  data.frame(
  id = 230,
  published = 'Yes',
  title = 'Legislatures, Leaders and Leviathans',
  author = 'Maldonado',
  year = 2012,
  journal = 'Social Science Quarterly',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1540-6237.2012.00895.x',
  table = 2,
  column = 2,
  indepvar = 'Size lower chamber',
  indepvar2 = 'N',
  depvar = 'Government Share of GDP',
  depvar2 = 'PCTGDP',
  coef = -0.0609,
  SE = 0.0117
))

dat <- rbind(dat,
  data.frame(
  id = 230,
  published = 'Yes',
  title = 'Legislatures, Leaders and Leviathans',
  author = 'Maldonado',
  year = 2012,
  journal = 'Social Science Quarterly',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1540-6237.2012.00895.x',
  table = 2,
  column = 2,
  indepvar = 'Size upper chamber',
  indepvar2 = 'K',
  depvar = 'Government Share of GDP',
  depvar2 = 'PCTGDP',
  coef = -0.04,
  SE = 0.0132
))

dat <- rbind(dat,
  data.frame(
  id = 220,
  published = 'Yes',
  title = 'The impact of within-party and between-party ideological dispersion on fiscal outcomes: evidence from Swiss cantonal parliaments',
  author = 'Bjedov, Lapointe, and Madiès',
  year = 2014,
  journal = 'Public Choice',
  web = 'https://link.springer.com/content/pdf/10.1007/s11127-013-0149-8.pdf',
  table = 3,
  column = 1,
  indepvar = 'Number of seats',
  indepvar2 = 'N',
  depvar = 'Spending per capita',
  depvar2 = 'ExpPC',
  coef = -0.003,
  SE = 0.01
))

dat <- rbind(dat,
  data.frame(
  id = 220,
  published = 'Yes',
  title = 'The impact of within-party and between-party ideological dispersion on fiscal outcomes: evidence from Swiss cantonal parliaments',
  author = 'Bjedov, Lapointe, and Madiès',
  year = 2014,
  journal = 'Public Choice',
  web = 'https://link.springer.com/content/pdf/10.1007/s11127-013-0149-8.pdf',
  table = 3,
  column = 2,
  indepvar = 'Number of seats',
  indepvar2 = 'N',
  depvar = 'Spending (%) GDP',
  depvar2 = 'PCTGDP',
  coef = -0.004,
  SE = 0.02
))

dat <- rbind(dat,
  data.frame(
  id = 208,
  published = 'Yes',
  title = 'Communication in federal politics: universalism, policy uniformity, and the optimal allocation of fiscal authority',
  author = 'Kessler',
  year = 2014,
  journal = 'Journal of Political Economy',
  web = 'https://www.jstor.org/stable/pdf/10.1086/676404.pdf?refreqid=excelsior%3A202fbd841dc5514e876482631872251b',
  table = 2,
  column = 4,
  indepvar = 'Council size',
  indepvar2 = 'N',
  depvar = 'Spending per capita',
  depvar2 = 'ExpPC',
  coef = 0.174,
  SE = 0.085
))

dat <- rbind(dat,
  data.frame(
  id = 176,
  published = 'Yes',
  title = 'Local intergovernmental competition and the law of 1/n',
  author = 'Crowley',
  year = 2015,
  journal = 'Southern Economic Association',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.4284/0038-4038-2013.075',
  table = 2,
  column = 1,
  indepvar = 'Lower chamber seats',
  indepvar2 = 'N',
  depvar = 'Per capita total expenditure',
  depvar2 = 'ExpPC',
  coef = -180.382,
  SE = 27.822
))

dat <- rbind(dat,
  data.frame(
  id = 176,
  published = 'Yes',
  title = 'Local intergovernmental competition and the law of 1/n',
  author = 'Crowley',
  year = 2015,
  journal = 'Southern Economic Association',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.4284/0038-4038-2013.075',
  table = 2,
  column = 1,
  indepvar = 'Upper chamber seats',
  indepvar2 = 'K',
  depvar = 'Per capita total expenditure',
  depvar2 = 'ExpPC',
  coef = 365.621,
  SE = 55.812
))

dat <- rbind(dat,
  data.frame(
  id = 3,
  published = 'Yes',
  title = 'The law of 1/n revisited: distributive politics, legislature size, and the costs of collective action',
  author = 'Crowley',
  year = 2019,
  journal = 'Southern Economic Journal',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1002/soej.12388',
  table = 2,
  column = 1,
  indepvar = 'Upper chamber (senate) seats',
  indepvar2 = 'K',
  depvar = 'Per capita total expenditure',
  depvar2 = 'ExpPC',
  coef = 8.21,
  SE = 4.051
))

dat <- rbind(dat,
  data.frame(
  id = 3,
  published = 'Yes',
  title = 'The law of 1/n revisited: distributive politics, legislature size, and the costs of collective action',
  author = 'Crowley',
  year = 2019,
  journal = 'Southern Economic Journal',
  web = 'https://onlinelibrary.wiley.com/doi/epdf/10.1002/soej.12388',
  table = 2,
  column = 1,
  indepvar = 'Lower chamber (senate) seats',
  indepvar2 = 'N',
  depvar = 'Per capita total expenditure',
  depvar2 = 'ExpPC',
  coef = -0.351,
  SE = 0.745
))

dat <- rbind(dat,
  data.frame(
  id = 8,
  published = 'Yes',
  title = 'Legislature size, local government expenditure and taxation, and public service access in indonesia',
  author = 'Lewis',
  year = 2019,
  journal = 'Studies in Comparative International Development',
  web = 'https://link.springer.com/content/pdf/10.1007/s12116-019-09278-1.pdf',
  table = 4,
  column = NA,
  indepvar = 'Legislature size',
  indepvar2 = 'N',
  depvar = 'Log per capita total expenditure',
  depvar2 = 'logExpPC',
  coef = -0.174,
  SE = (-0.174+0.245)/1.96
))

dat <- rbind(dat,
  data.frame(
  id = 42,
  published = 'Yes',
  title = 'Court-ordered redistricting and the law of 1/n',
  author = 'Lee and Park',
  year = 2018,
  journal = 'Public Choice',
  web = NA,
  table = 2,
  column = 1,
  indepvar = 'Lower',
  indepvar2 = 'N',
  depvar = 'Total expenditure per capita',
  depvar2 = 'ExpPC',
  coef = -0.851,
  SE = 1.395
))

dat <- rbind(dat,
  data.frame(
  id = 42,
  published = 'Yes',
  title = 'Court-ordered redistricting and the law of 1/n',
  author = 'Lee and Park',
  year = 2018,
  journal = 'Public Choice',
  web = NA,
  table = 2,
  column = 1,
  indepvar = 'Upper',
  indepvar2 = 'K',
  depvar = 'Total expenditure per capita',
  depvar2 = 'ExpPC',
  coef = 19.74,
  SE = 8.406
))

dat <- rbind(dat,
  data.frame(
  id = 82,
  published = 'Yes',
  title = 'Legislative fragmentation and government spending in presidential democracies: bringing ideological polarization into the picture',
  author = 'Höhmann',
  year = 2017,
  journal = 'Public Choice',
  web = 'https://link.springer.com/content/pdf/10.1007/s11127-017-0484-2.pdf',
  table = 2,
  column = 1,
  indepvar = 'Total number of seats in the legislature',
  indepvar2 = 'N',
  depvar = 'Log expenditure per capita',
  depvar2 = 'logExpPC',
  coef = -0.03,
  SE = 0.01
))

dat <- rbind(dat,
  data.frame(
  id = 102,
  published = 'Yes',
  title = 'The price of democracy? political representation structure and per capita expenditure in victorian local government',
  author = 'Drew and Dollery',
  year = 2017,
  journal = 'Urban Affairs Review',
  web = '10.1007/s11127-016-0369-9',
  table = 2,
  column = 1,
  indepvar = 'No. of representatives',
  indepvar2 = 'N',
  depvar = 'Ln Expenditure per capita',
  depvar2 = 'logExpPC',
  coef = 0.077,
  SE = 0.028
))

dat <- rbind(dat,
  data.frame(
  id = 132,
  published = 'Yes',
  title = 'Supermajority rule and bicameral bargaining',
  author = 'Lee',
  year = 2016,
  journal = 'Public Choice',
  web = 'https://link.springer.com/article/10.1007/s11127-016-0369-9',
  table = 3,
  column = 1,
  indepvar = 'Lower',
  indepvar2 = 'N',
  depvar = 'Per capita expenditure',
  depvar2 = 'ExpPC',
  coef = 0.0164,
  SE = 1.313
))

dat <- rbind(dat,
  data.frame(
  id = 132,
  published = 'Yes',
  title = 'Supermajority rule and bicameral bargaining',
  author = 'Lee',
  year = 2016,
  journal = 'Public Choice',
  web = 'https://link.springer.com/article/10.1007/s11127-016-0369-9',
  table = 3,
  column = 1,
  indepvar = 'Upper',
  indepvar2 = 'K',
  depvar = 'Per capita expenditure',
  depvar2 = 'ExpPC',
  coef = 38.44,
  SE = 19.23
))
```
